### ISSUE TITLE
Quartz not working in 1.18.2 papermc

### ISSUE THREAD

**Issue by michaeltebo** [darkhelmet-gaming/Quartz#1]
`[03:12:39] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:12:42] [Worker-Main-1/INFO]: Loaded 7 recipes
[03:12:47] [Server thread/INFO]: Starting minecraft server version 1.18.2
[03:12:47] [Server thread/INFO]: Loading properties
[03:12:49] [Server thread/INFO]: This server is running Paper version git-Paper-234 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c34fb09)
[03:12:49] [Server thread/INFO]: Server Ping Player Sample Count: 12
[03:12:49] [Server thread/INFO]: Using 4 threads for Netty based IO
[03:12:49] [Server thread/INFO]: Default game type: CREATIVE
[03:12:49] [Server thread/INFO]: Generating keypair
[03:12:49] [Server thread/INFO]: Starting Minecraft server on *:25565
[03:12:50] [Server thread/INFO]: Using epoll channel type
[03:12:50] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[03:12:50] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[03:12:59] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[03:13:09] [Server thread/WARN]: Legacy plugin SQLibrary v7.1 does not specify an api-version.
[03:13:10] [Server thread/WARN]: Legacy plugin Buscript v1.0-b19 does not specify an api-version.
[03:13:15] [Server thread/WARN]: Legacy plugin KillRewardsPlugin v1.3.3 does not specify an api-version.
[03:13:15] [Server thread/WARN]: Legacy plugin CitizensPlaceholderAPI v1.3 does not specify an api-version.
[03:13:17] [Server thread/WARN]: Legacy plugin MCCore v1.0.0 does not specify an api-version.
[03:13:18] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.9
[03:13:20] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1
[03:13:20] [Server thread/INFO]: [Skoice] Loading Skoice v2.0.2
[03:13:20] [Server thread/INFO]: [PluginManager] Loading PluginManager v2.7.1
[03:13:20] [Server thread/INFO]: [DisplayName] Loading DisplayName v2.2
[03:13:20] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[03:13:25] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.28-SNAPSHOT
[03:13:25] [Server thread/INFO]: [Quartz] Loading Quartz v2.2.0
[03:13:25] [Server thread/INFO]: [NoteBlockAPI] Loading NoteBlockAPI v1.6.1-SNAPSHOT
[03:13:25] [Server thread/INFO]: [SQLibrary] Loading SQLibrary v7.1
[03:13:25] [Server thread/INFO]: [GSit] Loading GSit v1.0.7
[03:13:26] [Server thread/INFO]: [GuiAPI] Loading GuiAPI v2.0
[03:13:26] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[03:13:26] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.4
[03:13:26] [Server thread/INFO]: [AntiCheatReloaded] Loading AntiCheatReloaded v1.10.3
[03:13:26] [Server thread/INFO]: ACR > Pool size is 1 threads
[03:13:26] [Server thread/INFO]: [Buscript] Loading Buscript v1.0-b19
[03:13:26] [Server thread/INFO]: [RiseCore] Loading RiseCore v1.0
[03:13:26] [Server thread/INFO]: [LiftReloaded] Loading LiftReloaded v2.4.0
[03:13:26] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.2-SNAPSHOT-bUNKNOWN
[03:13:26] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.29-SNAPSHOT (build 2493)
[03:13:26] [Server thread/INFO]: [MyDog] Loading MyDog v0.1.4-SNAPSHOT
[03:13:26] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v2.0.2-SNAPSHOT-119;f593530
[03:13:30] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@376d8fe8]
[03:13:30] [Server thread/INFO]: [Shopkeepers] Loading Shopkeepers v2.14.0
[03:13:31] [Server thread/INFO]: [Shopkeepers] Loaded all plugin classes (943 ms).
[03:13:31] [Server thread/WARN]: [Shopkeepers] Incompatible server version: v1_18_R2 (mappings: eaeedbff51b16ead3170906872fda334)
[03:13:31] [Server thread/WARN]: [Shopkeepers] Shopkeepers is trying to run in 'compatibility mode'.
[03:13:31] [Server thread/INFO]: [Shopkeepers] Check for updates at: https://dev.bukkit.org/projects/shopkeepers/
[03:13:32] [Server thread/INFO]: [Shopkeepers] Loading config.
[03:13:32] [Server thread/INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[03:13:32] [Server thread/INFO]: [Shopkeepers] Registering defaults.
[03:13:32] [Server thread/INFO]: [KillRewardsPlugin] Loading KillRewardsPlugin v1.3.3
[03:13:32] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect v2.19.4
[03:13:32] [Server thread/INFO]: [Multiverse-SignPortals] Loading Multiverse-SignPortals v4.2.1-SNAPSHOT-bUNKNOWN
[03:13:32] [Server thread/INFO]: [Multiverse-Inventories] Loading Multiverse-Inventories v4.2.3-SNAPSHOT-bUNKNOWN
[03:13:32] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.19.4
[03:13:32] [Server thread/INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild v2.19.4
[03:13:32] [Server thread/INFO]: [EconomyShopGUI] Loading EconomyShopGUI v4.3.1
[03:13:32] [Server thread/INFO]: [goPaint] Loading goPaint v3.1.0-56
[03:13:32] [Server thread/INFO]: [CitizensPlaceholderAPI] Loading CitizensPlaceholderAPI v1.3
[03:13:32] [Server thread/INFO]: [Multiverse-Portals] Loading Multiverse-Portals v4.2.2-SNAPSHOT-bUNKNOWN
[03:13:32] [Server thread/INFO]: [PvPManager] Loading PvPManager v3.9.4
[03:13:32] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.4
[03:13:32] [Server thread/INFO]: [Denizen] Loading Denizen v1.2.4-SNAPSHOT (build 1762-REL)
[03:13:32] [Server thread/INFO]: [EssentialsDiscord] Loading EssentialsDiscord v2.19.4
[03:13:32] [Server thread/INFO]: [ProMCUtilities] Loading ProMCUtilities v1.3-Trav
[03:13:32] [Server thread/INFO]: [QuickShop] Loading QuickShop v5.1.0.5
[03:13:32] [Server thread/INFO]: [QuickShop] QuickShop Reremake - Early boot step - Booting up
[03:13:33] [Server thread/INFO]: [QuickShop] [OK] Signature Verify
[03:13:33] [Server thread/INFO]: [QuickShop] [OK] Plugin Manifest Check
[03:13:33] [Server thread/INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[03:13:33] [Server thread/INFO]: [QuickShop] Reading the configuration...
[03:13:34] [Server thread/INFO]: [QuickShop] Loading messages translation over-the-air (this may need take a while).
[03:13:34] [Server thread/INFO]: [QuickShop] Translation over-the-air platform selected: Crowdin
[03:13:34] [Server thread/INFO]: [QuickShop] Checking for translation updates, this may need a while...
[03:13:47] [Server thread/INFO]: [QuickShop] Loading up integration modules.
[03:13:47] [Server thread/INFO]: [QuickShop] QuickShop Reremake - Early boot step - Complete
[03:13:47] [Server thread/INFO]: [MCCore] Loading MCCore v1.0.0
[03:13:47] [Server thread/INFO]: [Magic] Loading Magic v10.6.1-92a141d
[03:13:48] [Server thread/INFO]: [Magic] Loading modern compatibility layer for server version 1.18.2
[03:13:48] [Server thread/INFO]: [Magic] Async chunk loading API found
[03:13:48] [Server thread/INFO]: [Magic] Chat component API found
[03:13:48] [Server thread/INFO]: [Quests] Loading Quests v4.2.2-b${env.BUILD_NUMBER}
[03:13:48] [Server thread/INFO]: [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v4.2.2-SNAPSHOT-bUNKNOWN
[03:13:48] [Server thread/INFO]: [Konquest] Loading Konquest v0.9.0
[03:13:48] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:13:48] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.9
[03:13:50] [Server thread/INFO]:         __    
[03:13:50] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.9
[03:13:50] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[03:13:50] [Server thread/INFO]: 
[03:13:50] [Server thread/INFO]: [LuckPerms] Loading configuration...
[03:13:51] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[03:13:53] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[03:13:54] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[03:13:55] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 6353ms)
[03:13:55] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[03:13:55] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[03:13:55] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[03:13:55] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.4 which is not a depend or softdepend of this plugin.
[03:13:55] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[03:13:55] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[03:13:55] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[03:13:55] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[03:13:55] [Server thread/INFO]: [MyDog] Enabling MyDog v0.1.4-SNAPSHOT
[03:13:56] [Server thread/INFO]: [MyDog] Vault detected.
[03:13:56] [Server thread/INFO]: [MyDog] Loaded 9 dogs.
[03:13:56] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.0.2-SNAPSHOT-119;f593530
[03:13:56] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[03:13:56] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully
[03:13:56] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[03:13:57] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[03:13:58] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_18_R2.PaperweightFaweAdapter as the Bukkit adapter
[03:14:01] [Server thread/WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] An update for FastAsyncWorldEdit is available. You are 17 build(s) out of date.
You are running build 119, the latest version is build 136.
Update at https://www.spigotmc.org/resources/13932/
[03:14:01] [Server thread/INFO]: [Magic] Enabling Magic v10.6.1-92a141d
[03:14:01] [Server thread/INFO]: [Magic] EffectLib initialized
[03:14:04] [Server thread/INFO]: [Magic] Loaded 0 attributes
[03:14:04] [Server thread/INFO]: [Magic] Wand crafting is enabled
[03:14:04] [Server thread/INFO]: [Magic] Skin-based spell icons disabled
[03:14:04] [Server thread/INFO]: [Magic] Registered attributes: [target_fall_distance, regeneration, respiration, projectile_protection, bowpower, degrees, seconds, channeling, target_pitch, humidity, pitch, sharpness, jump, health_max, efficiency, target_luck, blindness, absorption, target_armor, loyalty, slow_digging, silk_touch, fire_resistance, unluck, invisibility, target_health_max, moon, air_max, slow, mana_max, sweeping, bowpull, damage, weeks, mending, epoch, protection, air, fast_digging, lure, punch, temperature, frost_walker, movement_speed_bps, power, riptide, health_boost, levitation, increase_damage, poison, health, target_temperature, binding_curse, yaw, mana, glowing, target_health, target_humidity, days, infinity, impaling, bad_omen, luck, thorns, hero_of_the_village, target_hunger, smite, location_x, unbreaking, location_y, target_mana, feather_falling, attack_damage, knockback, fire_aspect, luck_of_the_sea, knockback_resistance, saturation, conduit_power, location_z, target_air, bane_of_arthropods, soul_speed, night_vision, level, minutes, water_breathing, fall_distance, quick_charge, aqua_affinity, multishot, hunger, slow_falling, armor, blast_protection, confusion, damage_dealt, harm, piercing, fire_protection, target_yaw, dolphins_grace, speed, damage_resistance, weakness, heal, target_mana_max, hours, fortune, looting, target_air_max, movement_speed, play_time, depth_strider, xp, target_location_x, pi, target_location_y, vanishing_curse, target_knockback_resistance, target_location_z, time, flame, wither]
[03:14:04] [Server thread/INFO]: [Magic] Loaded 182 icons
[03:14:06] [Server thread/INFO]: [Magic] Loaded 12 effect lists
[03:14:06] [Server thread/INFO]: [Magic] Loaded 1402 items
[03:14:06] [Server thread/INFO]: [Magic] Loaded 198 wands
[03:14:06] [Server thread/INFO]: [Magic] Loaded 2 kits
[03:14:06] [Server thread/INFO]: [Magic] Loaded 10 classes
[03:14:06] [Server thread/INFO]: [Magic] Loaded 5 classes
[03:14:06] [Server thread/INFO]: [Magic] Loaded 73 mob templates
[03:14:06] [Server thread/INFO]: [Magic] Loaded 8 automata templates
[03:14:06] [Server thread/INFO]: [Magic] Loaded 0 customized worlds
[03:14:06] [Server thread/INFO]: [Magic] Activated BStats
[03:14:06] [Server thread/INFO]: [Magic] MobArena not found
[03:14:06] [Server thread/INFO]: [Magic] LibsDisguises found, mob disguises and disguise_restricted features enabled
[03:14:06] [Server thread/INFO]: Magic checking resource pack for updates: http://rp.elmakers.com/Magic-RP-1.18.zip
[03:14:06] [Server thread/INFO]: Preparing level "Smorgasbord"
[03:14:24] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[03:14:25] [Server thread/INFO]: Time elapsed: 619 ms
[03:14:25] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[03:14:25] [Server thread/INFO]: Time elapsed: 245 ms
[03:14:25] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[03:14:25] [Server thread/INFO]: Time elapsed: 250 ms
[03:14:25] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.1
[03:14:26] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[03:14:26] [Server thread/INFO]: [Skoice] Enabling Skoice v2.0.2
[03:14:27] [Server thread/INFO]: [Skoice] Plugin enabled!
[03:14:27] [Server thread/INFO]: [Skoice] Checking Version Now!
[03:14:35] [Server thread/INFO]: [net.dv8tion.jda.api.JDA] Login Successful!
[03:14:36] [JDA MainWS-WriteThread/INFO]: [net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
[03:14:37] [JDA MainWS-ReadThread/INFO]: [net.dv8tion.jda.api.JDA] Finished Loading!
[03:14:37] [Server thread/INFO]: [Skoice] JDA is running!
[03:14:37] [Server thread/INFO]: [PluginManager] Enabling PluginManager v2.7.1
[03:14:37] [Server thread/INFO]: [DisplayName] Enabling DisplayName v2.2
[03:14:37] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.28-SNAPSHOT
[03:14:37] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[03:14:37] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_18_R2
[03:14:37] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #1089
[03:14:37] [Server thread/INFO]: [LibsDisguises] Build Date: 22/03/2022 09:46
[03:14:37] [Server thread/WARN]: [LibsDisguises] If you own the plugin, place the premium jar downloaded from https://www.spigotmc.org/resources/libs-disguises.32453/ in plugins/LibsDisguises/
[03:14:37] [Server thread/INFO]: [LibsDisguises] You are running the free version, commands limited to non-players and operators. (Console, Command Blocks, Admins)
[03:14:55] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[03:14:55] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[03:14:55] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[03:14:55] [Server thread/INFO]: [Quartz] Enabling Quartz v2.2.0
[03:14:55] [Server thread/INFO]: [Quartz]: Initializing Quartz 2.2.0. by viveleroi.
[03:14:58] [Server thread/WARN]: org.quartz.SchedulerConfigException: Unable to instantiate class load helper class: org.quartz.simpl.CascadingClassLoadHelper [See nested exception: java.lang.ClassNotFoundException: org.quartz.simpl.CascadingClassLoadHelper]
[03:14:58] [Server thread/WARN]: 	at quartz-2.2.0-all.jar//org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:736)
[03:14:58] [Server thread/WARN]: 	at quartz-2.2.0-all.jar//org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559)
[03:14:58] [Server thread/WARN]: 	at quartz-2.2.0-all.jar//network.darkhelmet.quartz.Quartz.onEnable(Quartz.java:165)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[03:14:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666)
[03:14:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[03:14:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[03:14:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165)
[03:14:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[03:14:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:14:58] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.quartz.simpl.CascadingClassLoadHelper
[03:14:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[03:14:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[03:14:58] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:14:58] [Server thread/WARN]: 	at quartz-2.2.0-all.jar//org.quartz.impl.StdSchedulerFactory.loadClass(StdSchedulerFactory.java:1513)
[03:14:58] [Server thread/WARN]: 	at quartz-2.2.0-all.jar//org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:733)
[03:14:58] [Server thread/WARN]: 	... 13 more`

Quartz begins to load and fails before the server finishes initialization.

**Comment by viveleroi** [comment]
Where did you download the jar? Sounds like a build error.

**Comment by michaeltebo** [comment]
Downloaded and built .jar using GitHub repo. Should I just download the compiled .jar instead of building from code for v.2.1.0?

**Comment by michaeltebo** [comment]
Downloaded and installed .jar v.2.1.0, new error presented:

```
[11:42:28] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:42:31] [Worker-Main-1/INFO]: Loaded 7 recipes
[11:42:33] [Server thread/INFO]: Starting minecraft server version 1.18.2
[11:42:33] [Server thread/INFO]: Loading properties
[11:42:33] [Server thread/INFO]: This server is running Paper version git-Paper-234 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c34fb09)
[11:42:34] [Server thread/INFO]: Server Ping Player Sample Count: 12
[11:42:34] [Server thread/INFO]: Using 4 threads for Netty based IO
[11:42:34] [Server thread/INFO]: Default game type: CREATIVE
[11:42:34] [Server thread/INFO]: Generating keypair
[11:42:34] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:42:34] [Server thread/INFO]: Using epoll channel type
[11:42:35] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[11:42:35] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[11:42:40] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[11:42:50] [Server thread/WARN]: Legacy plugin SQLibrary v7.1 does not specify an api-version.
[11:42:50] [Server thread/WARN]: Legacy plugin Buscript v1.0-b19 does not specify an api-version.
[11:42:51] [Server thread/WARN]: Legacy plugin KillRewardsPlugin v1.3.3 does not specify an api-version.
[11:42:51] [Server thread/WARN]: Legacy plugin CitizensPlaceholderAPI v1.3 does not specify an api-version.
[11:42:52] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.9
[11:42:53] [Server thread/INFO]: [PancakeLibCore] Loading PancakeLibCore vBuild 2
[11:42:53] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1
[11:42:53] [Server thread/INFO]: [Skoice] Loading Skoice v2.0.2
[11:42:53] [Server thread/INFO]: [PluginManager] Loading PluginManager v2.7.1
[11:42:53] [Server thread/INFO]: [DisplayName] Loading DisplayName v2.2
[11:42:53] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[11:42:55] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.28-SNAPSHOT
[11:42:55] [Server thread/WARN]: [LibsDisguises] Loaded class com.comphenix.protocol.reflect.FieldAccessException from PancakeLibCore vBuild 2 which is not a depend or softdepend of this plugin.
[11:42:55] [Server thread/INFO]: [Quartz] Loading Quartz v1.0.0
...
[11:43:52] [Server thread/INFO]: [Quartz] Enabling Quartz v1.0.0
[11:43:52] [Server thread/INFO]: [Quartz]: Initializing Quartz 1.0.0. by viveleroi.
[11:43:53] [Server thread/INFO]: [org.quartz.impl.StdSchedulerFactory] Using default implementation for ThreadExecutor
[11:43:53] [Server thread/INFO]: [org.quartz.core.SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[11:43:53] [Server thread/INFO]: [org.quartz.core.QuartzScheduler] Quartz Scheduler v.2.3.0 created.
[11:43:53] [Server thread/INFO]: [org.quartz.simpl.RAMJobStore] RAMJobStore initialized.
[11:43:53] [Server thread/INFO]: [org.quartz.core.QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.3.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[11:43:53] [Server thread/INFO]: [org.quartz.impl.StdSchedulerFactory] Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
[11:43:53] [Server thread/INFO]: [org.quartz.impl.StdSchedulerFactory] Quartz scheduler version: 2.3.0
[11:43:53] [Server thread/INFO]: [Quartz]: Loaded 21 enabled commands.
[11:43:53] [Server thread/ERROR]: Error occurred while enabling Quartz v1.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: Failed to parse cron expression. Invalid chars in expression! Expression: DEC Invalid chars: DEC
	at network.darkhelmet.quartz.cronutils.parser.CronParser.parse(CronParser.java:131) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.Quartz.scheduleJob(Quartz.java:280) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.Quartz.loadSchedules(Quartz.java:259) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.Quartz.onEnable(Quartz.java:167) ~[quartz-2.1.0-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-234]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-234]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid chars in expression! Expression: DEC Invalid chars: DEC
	at network.darkhelmet.quartz.cronutils.parser.FieldParser.stringToInt(FieldParser.java:263) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.FieldParser.mapToIntegerFieldValue(FieldParser.java:231) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.FieldParser.parseOn(FieldParser.java:165) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.FieldParser.noSpecialCharsNorStar(FieldParser.java:134) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.FieldParser.parse(FieldParser.java:70) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.CronParserField.parse(CronParserField.java:89) ~[quartz-2.1.0-all.jar:?]
	at network.darkhelmet.quartz.cronutils.parser.CronParser.parse(CronParser.java:127) ~[quartz-2.1.0-all.jar:?]
	... 14 more
[11:43:53] [Server thread/INFO]: [Quartz] Disabling Quartz v1.0.0
```

**Comment by viveleroi** [comment]
Did you alter the config? Look for a cron string with `DEC` in it. The error is

> Failed to parse cron expression. Invalid chars in expression! Expression: DEC Invalid chars: DEC

But there's no default config that should be using that.

**Comment by michaeltebo** [comment]
Checked and rewrote the line called for in the .conf file. Used the CRON expression builder noted in the config. Works. Thank you for your time.
